Nordix/metal3-clusterapi-docs

airship/kubeadm-airship-gap-analysis.md

Studies of metallb and keepalived load balancers

---

airship/kubeadm-airship-gap-analysis.md

Added entry for study of pause container selection

---

airship/kubeadm-airship-gap-analysis.md

Add CA Rotation findings with Kubeadm (Jira Issue #AIR-138 )

Add #AIR-138(CA rotation) study findings

---

airship/AIR-139_140_loadbalancers.md
airship/AIR-141_runtimeclass.md
airship/AIR-146_non-default-ip-for-master.md
airship/AIR-147_docker-operation-with-sha256.md
airship/AIR-148_pause-containers-selection.md
airship/AIR-149_k8s-image-and-tags-selection.md

- Also, added sample init and join kubeadm configurations files

Added objective to issues

---

airship/AIR-142_enrypt-data-at-rest_and_provide-more-certs.md

Encryption at rest and providing pre-generated certificate experiment findings is updated

Update jira issue #AIR-142 findings

---

capi-dev/README.md

Added a readme file which contains instructions for running the capi-dev environment

Add capi-dev read me

---

airship/AIR-138_kubeadm-rotating-ca.md

Update the certificate renewal observations

Update the certificate renewal observations

---

airship/AIR-138_kubeadm-rotating-ca.md

1. Added Key objective
2. Anwar's review comments are addressed

Add key objectives section in AIR-138

---

capi-dev/README.md

Adds docker version information.

Add docker version info

---

pivoting/Pivoting_Study.md

The document helps to reproduce the pivoting study environment.

Pivoting Study Environment

---

v1alpha3/v1a3_study.md

This study gives an overview of upcoming cluster-api v1alpha3 changes.
Co-author: jaakko.kuuskoski@est.tech

Cluster-api v1alpha3 study for CAPBM

---

01_HAProxy-DS-separate-CM/README.md
01_HAProxy-DS-separate-CM/hapxy-ok-ds.yaml
lb-haproxy-study/LB-HAProxy-ds-sc/01_HAProxy-DS-separate-CM/README.md
lb-haproxy-study/LB-HAProxy-ds-sc/01_HAProxy-DS-separate-CM/hapxy-ok-ds.yaml
lb-haproxy-study/LB-HAProxy-ds-sc/README.md
lb-haproxy-study/LB-HAProxy-ds-sc/Vagrantfile
lb-haproxy-study/LB-HAProxy-ds-sc/config.yaml
lb-haproxy-study/LB-HAProxy-ds-sc/haproxy.cfg
lb-haproxy-study/LB-HAProxy-ds-sc/hapxy-ok-ds.yaml
lb-haproxy-study/LB-HAProxy-ds-sc/run_me.sh
lb-haproxy-study/LB-HAProxy-ds-sc/setup_k8s_binaries.sh
lb-haproxy-study/README.md

Co-authored-by: mika.koskimaki@est.tech
Co-authored-by: anwar.hassen@est.tech

Lb haproxy study

---

capi-tilt/README.md

This PR add more information of the problems using Kind v0.8.0.

This patch adding note to Kind installation instructions.

---

capo/capo-security-groups.md

Add documentation on using existing security groups and creating new ones

Add documentation on using existing security groups and creating new ones

---

ironic-features/ironic_features.md

The summary contains the list of new features from 2021.09.29 to
2022.03.15.

Add summary about new ironic features

---

security/openssf-scorecards.md

Do OpenSSF Scorecard evaluations to projects beloning to Metal3 ecosystem.

security: add openssf scorecard evaluation

---

security/container-privileges.md

Also, fix some formatting, and misinformation on dev-env containers.

security: add namespaces to container-privileges

---

security/go-mod-and-go-sum.md

Add a README on go.mod and go.sum difference, and how the files should or should not be used for vulnerability scanning, or licensing.

add a README on go mod/go sum differences

---

security/tls-1.3.md

Update tls1.3 support document to match situation now in Sep 2024.

update tls1.3 support document

---

OWNERS_ALIASES

Remove mboukhalfa and furkatgofurov7 from approvers in Nordix repos.

remove mboukhalfa and furkatgofurov7 from approvers

---

OWNERS_ALIASES

Add Peppi-Lotta and Feruz to approvers.

add Peppi-Lotta and Feruz to approvers

---

n+3-upgrade/n+3-upgrade.md

This doc will describe the step by step instruction to have N+3 upgrade

N+3 upgrade Instructions
