airship/kubeadm-airship-gap-analysis.md

Updates the document with test Results of non-default IP/network experiment in kubeadm.
Jira Issue #AIR-146

Test non-default IP/network in kubeadm

---

capi-tilt/README.md

Since Cluster-API is an open source project, anyone can clone it. Even it is fine to use SSH to clone the repo, using HTTPS allows cloning without ssh keypair, making it easier in some cases, e.g., Cloning the repo from a VM.

Clone the cluster-api by HTTPs instead of SSH

---

capi-tilt/README.md
capi-tilt/controlplane.yaml
capi-tilt/machine-deployment.yaml

Some instructions were misleading and this PR corrects them to mitigate the confusion during testing. Controlplane.yaml and machine-deployment.yaml updated to use Kubernetes v1.18.0

Update the instructions

---

ca-rotation-study/README.md
ca-rotation-study/cluster-info.yaml
ca-rotation-study/new-dockermachinetemplate.yaml
ca-rotation-study/update-ca.yaml
ca-rotation-study/update-controlplane.yaml
ca-rotation-study/update-etcd.yaml
ca-rotation-study/update-proxy.yaml
ca-rotation-study/update-worker.yaml

The study investigates how to rotate the CAs used in a kubernetes cluster to use new cryptographic secrets. It also contains a list of tests done during the investigation. The required files for the tests are included as well.

Add study on CA rotation

---

single-server/single-server.md

This is POC study following the [Single Server Deployment Study](https://docs.google.com/document/d/1Fgiz-TRBn4L4Ur00j-v7TcloL6v6L86Xc4IbFr3Qde4/edit?ts=5e86e740#heading=h.adzuc1cjggcf) made in April, 2020. Purpose of the study is to find out what are the steps to restore cluster status after OS upgrade in single server deployment.

Single server study

---

opensuse-ipa/opensuse-15.3-ipa.md

This documentation adds the description on how to modify
the IPA image building process in order to be able to build a bootable
IPA image based on OpenSUSE Leap 15.3 .

Describe how to build IPA based on Opensuse 15.3

---

topolvm/README.md

This adds instructions for how to build and test TopoLVM on a Citycloud VM.

Add TopoLVM instructions

---

ironic/ironic_deployment_investigation.md

Update the doc to state that it is optional to open ironic ports on either all interfaces or only ironic-related interface.

How to not open ports on all interfaces

---

meta-provider/meta-provider/BYOH+metal3/Vagrantfile
meta-provider/meta-provider/BYOH+metal3/byoh-components.yaml
meta-provider/meta-provider/BYOH+metal3/metal3-cluster.yaml
meta-provider/meta-provider/BYOH+metal3/metal3-workers.yaml
meta-provider/meta-provider/README.md
meta-provider/meta-provider/nested+metal3/metal3_config.sh
meta-provider/meta-provider/nested+metal3/nested-components.yaml
meta-provider/meta-provider/nested+metal3/v1alpha5_cluster_ubuntu.yaml
meta-provider/meta-provider/nested+metal3/v1alpha5_workers_ubuntu.yaml

The goal is to combine multiple CAPI infrastructure providers to create
a single cluster. Ideally, the control plane should run as pods in the
management cluster while the worker nodes consist of Metal3Machines.

Add investigation about meta provider

---

security-tools/security-scan-tools.md

This document will describe how to use **kube-hunter** and **kube-bech** in metal3-dev-env as security vulnerability tools. The information can be used for configuring them in future with metal3-dev-env.

Add documentation for security scanning tools for future usages in metal3-dev-env

---

PlatformAwareEnergy/README.md
README.md
ca-rotation-study/README.md
hack/markdownlint.sh
ironic/ironic_deployment_investigation.md
lb-haproxy-study/README.md
meta-provider/README.md
metal3/AIR-146_non-default-ip-for-master.md
upgrade/README.md

mdl 0.12 moves unordered list indentation from 2 spaces to 3 spaces due Kramdown requirements.
Pin markdownlint image to 0.12 (with SHA), and fix all markdown comply with mdl 0.12.

markdown: pin mdl to 0.12.0 and fix complaints

---

Support/Multitenancy/Ironic_bmo-mult-instances/01-vm-setup.sh
Support/Multitenancy/Ironic_bmo-mult-instances/05-apply-manifests.sh
Support/Multitenancy/Ironic_bmo-mult-instances/clean.sh
Support/Multitenancy/Ironic_bmo-mult-instances/dowanload-node-image.sh

- Change network config to keyfile format
- The recent libvirt package fails to create a domain with `nvram`
- Increase the waiting time before applying the cluster template
- Add download node image script
- Add cleanup script

Fix multiple ironic scripts

---

security/tls-1.3.md

Document TLS 1.3 support in Metal3 ecosystem and the state of the TLS at the time of writing. Some background info on Golang's TLS support is added for context.

security: add TLS 1.3 support documentation

---

security/container-privileges.md

Update container-privileges.md to match CAPM3 v1.4.0 release. In this
release, we have applied a lot of security contexts to harden up the
container images and deployment, including ironic-image.

update container-privileges.md in v1.4.0

---

security/kubelogin-poc/README.md
security/kubelogin-poc/k8s/config.yaml
security/kubelogin-poc/k8s/dex.yaml
security/kubelogin-poc/k8s/kind.conf
security/kubelogin-poc/k8s/kubeconfig
security/kubelogin-poc/k8s/openldap.txt
security/kubelogin-poc/k8s/openldap.yaml

This POC is about enabling `int128/kubelogin`, ie. `kubectl-oidc_login` integration to k8s apiserver, while running Dex as OIDC provider backed by (open)LDAP. k8s cluster provided by Kind.

security: add Kubelogin POC

---

hack/markdownlint.sh

Bump markdownlint to 0.13.0.
Also, rewrite the rule config to ignore the issues instead of listing the allowed ones. Makes it clearer and more futureproof. Actual fixing of the issues should be done in some future commit.
TODO: bump in project-infra when all repos are bumped.
/hold 
until https://github.com/metal3-io/project-infra/pull/600 is merged, so the rule config is actually tested.

bump markdownlint to 0.13.0

---

.markdownlint-cli2.yaml
hack/markdownlint.sh

Switch markdownlint container to markdownlint-cli2. This CLI version supports the enable/disable rules in markdown files and allows us to ignore issues locally, not just globally.
- project-infra PR https://github.com/metal3-io/project-infra/pull/619 needs to merge for markdownlint here to pass

switch markdownlint container to markdownlint-cli2

---

security/tls-1.3.md

This commit updates:
- TLS profile of Ironic/IPA
- TLS profile of etcd

update TLS profile document of the Metal3 stack

---

security/container-signing-poc/Makefile
security/container-signing-poc/README.md
security/container-signing-poc/kyverno/Makefile
security/container-signing-poc/kyverno/README.md
security/container-signing-poc/kyverno/policy/kyverno-policy.yaml
security/container-signing-poc/kyverno/scripts/kind-cluster.sh
security/container-signing-poc/notation/.gitignore
security/container-signing-poc/notation/LICENSE
security/container-signing-poc/notation/Makefile
security/container-signing-poc/notation/README.md
security/container-signing-poc/notation/cmd/notation-external-signer/.gitignore
security/container-signing-poc/notation/cmd/notation-external-signer/key.go
security/container-signing-poc/notation/cmd/notation-external-signer/main.go
security/container-signing-poc/notation/cmd/notation-external-signer/metadata.go
security/container-signing-poc/notation/cmd/notation-external-signer/sign.go
security/container-signing-poc/notation/examples/.gitignore
security/container-signing-poc/notation/examples/read-signature-from-file.sh
security/container-signing-poc/notation/examples/rsassa-pss-sha512.sh
security/container-signing-poc/notation/examples/trustpolicy.json
security/container-signing-poc/notation/go.mod
security/container-signing-poc/notation/go.sum
security/container-signing-poc/oras/.gitignore
security/container-signing-poc/oras/Makefile
security/container-signing-poc/oras/README.md

Proof-of-concept focusing on enabling container signing with any signing backend.
1. Add Notation External Signer plugin and sign images with that
2. Move signatures from "CI" to "production" registry with Otas
3. Validate the signatures runtime with Kyverno admission control
TODO:

add container signing POC

---

rook-ceph-upgrade/rook-ceph-upgrade.md

Instruction to upgrade rook/ceph from downstream version to the master branch and latest release branch.

Upgrade test instructions for rook and ceph

---

security/container-signing-poc/Makefile
security/container-signing-poc/README.md
security/container-signing-poc/cosign/.gitignore
security/container-signing-poc/cosign/Makefile
security/container-signing-poc/cosign/README.md
security/container-signing-poc/cosign/scripts/gencrt.sh
security/container-signing-poc/kyverno/Makefile
security/container-signing-poc/kyverno/README.md
security/container-signing-poc/kyverno/policy/kyverno-policy-cosign.yaml
security/container-signing-poc/kyverno/policy/kyverno-policy-notation.yaml
security/container-signing-poc/kyverno/scripts/kind-cluster.sh
security/container-signing-poc/notation/README.md
security/container-signing-poc/notation/examples/.gitignore

Add cosign as option to container-signing-poc. This allows comparison between cosign and notation for using external signing service.
Note that `make e2e` is quite a mess now and should be refactored in a follow-up. `make test` directly in `kyverno` is working better.

add cosign as option to container-signing-poc

---

security/container-signing-poc/cosign/Makefile

make argument `CERT_SCRIPT=<your script here>` to replace the default certificate generation via `./gencrt.sh`, so you can use your own certs instead, or keep using the same ones each time.
Just make sure they're named the same (ca, sub-ca, leaf), with crt suffix (leaf must have key as well), and concatenate sub-ca and ca to certificate_chain.pem.
Also, remove regex identity from verification to allow custom certs with other identities to work.

allow using your own certs in container-signing-poc

---

security/keylime-poc/README.md
security/keylime-poc/agent-with-swtpm/Dockerfile
security/keylime-poc/agent-with-swtpm/dbus-policy.conf
security/keylime-poc/agent-with-swtpm/start.sh
security/keylime-poc/compose/.gitignore
security/keylime-poc/compose/README.md
security/keylime-poc/compose/agent.conf
security/keylime-poc/compose/compose.yml
security/keylime-poc/compose/logging.conf
security/keylime-poc/compose/registrar.conf
security/keylime-poc/compose/tenant.conf
security/keylime-poc/compose/tenant.sh
security/keylime-poc/compose/verifier.conf

Make a Proof of Concept of Keylime is k8s cluster.
This part 1 is adding Keylime in Docker Compose. This doubles as the keylime service part in part 2, where agent(s) move to k8s. Agent image is having SWTPM module built-in, so this environment is portable across machines, regardless of their TPM chip or lack there of.
This POC is needed as the concept of having Keylime Tenant/Verifier/Registrar outside k8s cluster, but Keylime Agent in k8s cluster and being accessed via Ingress/LoadBalancer IP, is something Keylime maintainers did not think originally as a use-case. This has several issues with the current design, and while there is a proposal/ study for changing from "pull model" to "push model", it is miles away and this POC tries to find out the minimal changes needed to make the …

add keylime-poc part 1: docker compose and agent with swtpm

---

OWNERS_ALIASES

@mquhuy is not active as an approver in Nordix repos anymore. Thanks Huy for all your contributions.
Signed-off-by: Kashif Khan <kashif.khan@est.tech>

Remove @mquhuy from approvers

---

security/kubelogin-poc/README.md
security/kubelogin-poc/kubeconfig.device-code.example
security/kubelogin-poc/kubeconfig.password.example
security/kubelogin-poc/run.sh

Update Kubelogin POC to include offline_access scope for enabling refresh tokens. Especially device-code flow is annoying if the idToken would expire as it would lead to another browser login.
Also cleanup the kubeconfig example to use real values from run.sh for device-code flow.

update kubelogin-poc to include offline_access
